# Generated by Django 4.1.2 on 2022-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_alter_genericpage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
