# Generated by Django 4.1.2 on 2022-11-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_socialmediasettings_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(max_length=100),
        ),
    ]
